// <auto-generated />
using Agrosvet.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace agrosvet.api.Migrations
{
    [DbContext(typeof(AgrosvetDbContext))]
    partial class AgrosvetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Agrosvet.Api.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Agrosvet.Api.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Agrosvet.Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Seme"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Đubrivo"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Zaštita bilja"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Alati"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Seme povrća",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Seme žitarica",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Mineralna đubriva",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 8,
                            Name = "Organska đubriva",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 9,
                            Name = "Herbicidi",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 10,
                            Name = "Fungicidi",
                            ParentCategoryId = 3
                        });
                });

            modelBuilder.Entity("Agrosvet.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("active");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 6,
                            Description = "Visokoprinosni hibrid kukuruza.",
                            Name = "Seme Kukuruza",
                            Price = 1500.00m,
                            Status = "active"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 7,
                            Description = "Univerzalno đubrivo za sve kulture.",
                            Name = "Mineralno Đubrivo NPK",
                            Price = 2500.00m,
                            Status = "active"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 9,
                            Description = "Sredstvo za suzbijanje korova.",
                            Name = "Herbicid Total",
                            Price = 1200.00m,
                            Status = "active"
                        });
                });

            modelBuilder.Entity("Agrosvet.Api.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            Url = "/images/seme-kukuruza-1.jpg"
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 2,
                            Url = "/images/npk-djubrivo.jpg"
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 3,
                            Url = "/images/herbicid-total.jpg"
                        });
                });

            modelBuilder.Entity("Agrosvet.Api.Models.CartItem", b =>
                {
                    b.HasOne("Agrosvet.Api.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("Agrosvet.Api.Models.Category", b =>
                {
                    b.HasOne("Agrosvet.Api.Models.Category", "ParentCategory")
                        .WithMany("Subcategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Agrosvet.Api.Models.Product", b =>
                {
                    b.HasOne("Agrosvet.Api.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Agrosvet.Api.Models.ProductImage", b =>
                {
                    b.HasOne("Agrosvet.Api.Models.Product", "Product")
                        .WithOne("Image")
                        .HasForeignKey("Agrosvet.Api.Models.ProductImage", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Agrosvet.Api.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Agrosvet.Api.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("Agrosvet.Api.Models.Product", b =>
                {
                    b.Navigation("Image");
                });
#pragma warning restore 612, 618
        }
    }
}
